config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :restaurants do
    resources :reviews, only: [:index, :new, :create]
  end
  resources :reviews, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  CATEGORY = ["Chinese", "Italian", "Japanese", "French", "Belgian", "American"]
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, :inclusion => { :in => 0..5, :message => "Choose between 0 to 5" }
  validates :rating, :presence => { :message => "Required" }
  validates :rating, :numericality => { :message => "Type a number please" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]

  # GET /restaurants or /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy!

    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: "Restaurant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :category, :phone_number)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    respond_to do |format|
      if @review.save
        format.html { redirect_to review_url(@review), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy!

    respond_to do |format|
      format.html { redirect_to review_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:rating, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category, collection: Restaurant::CATEGORY %>
    <%= f.input :phone_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-success" %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>">
  <p>
    <strong>Name :</strong>
    <%= restaurant.name %>
  </p>

  <p>
    <strong>Address :</strong>
    <%= restaurant.address %>
  </p>

  <p>
    <strong>Category :</strong>
    <%= restaurant.category %>
  </p>

  <p>
    <strong>Phone number :</strong>
    <%= restaurant.phone_number %>
  </p>
</div>

app/views/restaurants/edit.html.erb
<div class="container">
  <h1 class="text-center fw-bold text-uppercase">Editing</h1>

  <%= render "form", restaurant: @restaurant %>
  <br>

  <div>
    <%= link_to "🔙 Back", restaurants_path, class:"btn btn-primary" %>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container ">
  <p style="color: green"><%= notice %></p>

  <h1 class="text-center fw-bold text-uppercase">Restaurants</h1>
  <br>
  <%= link_to "➕ Add restaurant", new_restaurant_path, class:"btn btn-success" %>
  <br><br>
  <div id="restaurants">
  <ul class="list-group">
    <% @restaurants.each do |restaurant| %>
      <!-- Restaurant Item -->
      <li id="show_restaurant" class="list-group-item">
        <!-- Restaurant Info -->
        <div class="mb-2 mt-2"><%= render restaurant %></div>
        <!-- Restaurant Btn -->
        <div class="d-flex justify-content-between mb-2">
          <%= link_to "Details", restaurant, class: "btn btn-secondary" %>
          <%= link_to "Edit review", restaurant, class: "btn btn-warning" %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1 class="text-center fw-bold text-uppercase">New restaurant</h1>

  <%= render "form", restaurant: @restaurant %>

  <br>

  <div>
    <%= link_to "🔙 Back", restaurants_path, class:"btn btn-primary" %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @restaurant %>
  <p><strong>Reviews :</strong></p>

  <ul class="list-group">
    <% @restaurant.reviews.each do |review| %>
      <!-- Review Item -->
      <li id="show_review" class="list-group-item d-flex align-items-center">
        <!-- Rating Block -->
        <div class="rating-block m-3">
          <span class="text-black fw-bold"><%= review.rating %>⭐</span>
        </div>
        <!-- Review Content -->
        <div class="review-content flex-grow-1">
            <p class="mb-1"><%= review.content %></p>
        </div>
        <!-- Delete Button -->
        <div class="delete-block p-3">
            <%= link_to "❌",
              review_path(review),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"
              }, class:"btn btn-outline-danger"
            %>
        </div>
      </li>
    <% end %>
  </ul>

  <div class="d-flex justify-content-between">
    <%= link_to "🔙 Back", restaurants_path, class:"btn btn-primary" %>
    <%= link_to "Change informations 🖊️", edit_restaurant_path(@restaurant), class:"btn btn-warning" %>
    <%= button_to "Delete 🗑️", @restaurant, method: :delete, class:"btn btn-danger" %>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for[@restaurant, @review] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :rating %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div id="<%= dom_id review %>">
  <p>
    <strong>Rating:</strong>
    <%= review.rating %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= review.content %>
  </p>

</div>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Show this review", @review %> |
  <%= link_to "Back to reviews", reviews_path %>
</div>

app/views/reviews/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reviews</h1>

<div id="reviews">
  <% @reviews.each do |review| %>
    <%= render review %>
    <p>
      <%= link_to "Show this review", review %>
    </p>
  <% end %>
</div>

<%= link_to "New review", new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Back to reviews", reviews_path %>
</div>

app/views/reviews/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @review %>

<div>
  <%= link_to "Edit this review", edit_review_path(@review) %> |
  <%= link_to "Back to reviews", reviews_path %>

  <%= button_to "Destroy this review", @review, method: :delete %>
</div>